### ISSUE TITLE
Kotti fails to return balance

### ISSUE THREAD

**Issue by simsim314** [ethereum-classic-cooperative/ethercluster#11] opened 2019-07-24 16:49 UTC
The attached html file is failing to log the balance. The account is listed on the Kotti Faucet, and the code works with other blockchains (I've no other way to debug Kotti account). 

**The error is:**

Access to fetch at 'https://www.ethercluster.com/kotti' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

[KottiFail.zip](https://github.com/ethereum-classic-cooperative/ethercluster/files/3427896/KottiFail.zip)

**Comment by YazzyYaz** [comment] 2019-07-24 21:18
I checked your call and you indeed don't have any balance on this address:
```js
> web3.fromWei(eth.getBalance("0x31768864ee052b68dac2ba51a4531ecfc61b307f"), "ether")
0
```

If you would like some Kotti ETC on that address, I can send it to you personally. If you applied to the Kotti Faucet and didn't receive any from it, the issue is with the Faucet, not Ethercluster.

Observe this call I make via Ethercluster to the Kotti Faucet address I know has Kotti ETC via Curl:

```sh
curl --data '{"method":"eth_getBalance","params":["0xE1f452375408A4a63D3d52618b52F7b4Ed112E0E"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST https://www.ethercluster.com/kotti

{"jsonrpc":"2.0","result":"0x10f1ad11b9100840000","id":1}
```

Notice the JSON-RPC response gives back `0x10f1ad11b9100840000` as a hex result. Now, we go to a hex-to-decimanl converter [here](https://www.rapidtables.com/convert/number/hex-to-decimal.html)

Converting the result gives back `5001000000000000000000`
That's the balance in Weis. Dividing it by 1e18 gives `5001` Kotti ETC, which is the correct balance. I can verify it by attaching to a local node I'm running and doing to following in the JS console:
```js
> web3.fromWei(eth.getBalance("0xE1f452375408A4a63D3d52618b52F7b4Ed112E0E"), "ether")
5001
```

Your problem is that your balance is 0 when you expect it to be something else. If you need Kotti, I can send you some to an address of your choosing. Closing this issue as it's not a bug but an issue with Kotti faucet and not Ethercluster.

**Closed as completed by YazzyYaz** 2019-07-24 21:18 UTC
