### ISSUE TITLE
SSL Error when using Python web3

### ISSUE THREAD

**Issue by tpmccallum** [ethereum-classic-cooperative/ethercluster#14] opened 2019-08-21 06:06 UTC
**Describe the bug**
Getting a SSLError when accessing ethercluster RPC endpoint via Python web3

**To Reproduce**
```
from web3 import Web3, HTTPProvider
web3 = Web3(HTTPProvider("https://www.ethercluster.com/etc"))
latestBlockNumber = web3.eth.getBlock('latest').number
```
Returns the following
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 472, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1808, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1548, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
...
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.ethercluster.com', port=443): Max retries exceeded with url: /etc (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

**Comment by YazzyYaz** [comment] 2019-08-22 00:08
@tpmccallum thank you for reporting this.

I believe the issue is because you're trying to make a client-side request without knowing the cert's path, as in this issue: https://stackoverflow.com/questions/14746857/how-to-find-the-path-to-a-ssl-cert-file

The way to work around it is to skip SSL certificate verification when you connect to Ethercluster.

```python
>>> web3 = Web3(HTTPProvider("https://www.ethercluster.com/etc", request_kwargs={'verify': False}))
>>> latestBlockNumber = web3.eth.getBlock('latest').number
>>> latestBlockNumber
8640087
```

I believe the only way to very SSL to prove the server's identity is via a key from the client-side, but since this project is a public SSL endpoint for people to use for free to test out the technology, we don't currently provide an API key.

So, adding this kwargs `request_kwargs={'verify': False}` helps skip past it. You can always manually check the certificate on the website https://www.ethercluster.com/etc

Furthermore, we also have the docs to recreate the project if you're building a large scale dapp that will need to do more auth. But, for testing purposes, the kwarg I point to above should do the trick.

Let me know if you have any more questions. I'm closing this issue for now. Thank you for filing this.

**Closed as completed by YazzyYaz** 2019-08-22 00:08 UTC

**Comment by tpmccallum** [comment] 2019-08-22 01:37
Hi @YazzyYaz 
This is working now.
Thank you so much!

**Comment by YazzyYaz** [comment] 2019-09-11 01:19
@tpmccallum btw, I have fixed the SSL issue in Ethercluster. Turns out there's a bug in Kubernetes I missed.

Now, you can run the same original code without `verify`.

This code works in Python console:
```
>>> from web3 import Web3, HTTPProvider
>>> web3 = Web3(HTTPProvider("https://www.ethercluster.com/etc"))
>>> latestBlockNumber = web3.eth.getBlock('latest').number
>>> latestBlockNumber
8762678
```

**Comment by yury-dubinin** [comment] 2023-01-04 15:52
Hey @YazzyYaz what is this `a bug in Kubernetes I missed` about? could you please point me to the MR with that fix if possible?
